const ListOfOrchids = [
  {
    id: 1,
    name: "Taichung Beauty",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1747483588146-2480d1f0104e?auto=format&fit=crop&w=900&q=80",
    color: "Pink",
    origin: "Taiwan",
    category: "Cattleya",
    description:
      "A rare Cattleya hybrid known for its deep pink petals and a strong sweet fragrance that fills the room in the morning.",
    light: "Bright indirect light",
    water: "Weekly, once the mix dries",
    temperature: "18-28 C",
  },
  {
    id: 2,
    name: "White Moon",
    rating: 4,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1677341881933-ace966e3ffa2?auto=format&fit=crop&w=900&q=80",
    color: "White",
    origin: "Thailand",
    category: "Dendrobium",
    description:
      "Pure white blooms on cane-like stems. Easy for beginners and reliable in a warm, humid corner.",
    light: "Filtered light",
    water: "Every 8-10 days",
    temperature: "16-27 C",
  },
  {
    id: 3,
    name: "Purple Queen",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1744622811364-6f890f936c8f?auto=format&fit=crop&w=900&q=80",
    color: "Purple",
    origin: "Vietnam",
    category: "Phalaenopsis",
    description:
      "Moth orchid with a deep violet lip and long arching sprays that stay in flower for months.",
    light: "Medium indirect light",
    water: "Weekly",
    temperature: "18-29 C",
  },
  {
    id: 4,
    name: "Golden Sun",
    rating: 4,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1615081715642-457053922ee9?auto=format&fit=crop&w=900&q=80",
    color: "Yellow",
    origin: "Japan",
    category: "Oncidium",
    description:
      "A dancing lady orchid with dozens of small butter-yellow flowers on branching spikes.",
    light: "Bright indirect light",
    water: "Twice a week",
    temperature: "18-30 C",
  },
  {
    id: 5,
    name: "Red Dragon",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1674314918932-a74333bfaad5?auto=format&fit=crop&w=900&q=80",
    color: "Red",
    origin: "China",
    category: "Cymbidium",
    description:
      "Bold crimson flowers on a sturdy plant that tolerates cooler rooms better than most orchids.",
    light: "Bright light",
    water: "Weekly",
    temperature: "12-24 C",
  },
  {
    id: 6,
    name: "Blue Diamond",
    rating: 4,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1751444041935-1d3d0d6fe93e?auto=format&fit=crop&w=900&q=80",
    color: "Blue",
    origin: "Singapore",
    category: "Vanda",
    description:
      "Unusual blue-violet tessellated petals. Vandas need airier roots, so keep the mix loose.",
    light: "Very bright light",
    water: "Daily misting",
    temperature: "20-32 C",
  },
  {
    id: 7,
    name: "Orange Delight",
    rating: 3,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1740478105319-5e7226ab0a91?auto=format&fit=crop&w=900&q=80",
    color: "Orange",
    origin: "Malaysia",
    category: "Cattleya",
    description:
      "Warm apricot tones on medium blooms. A forgiving first orchid for a new grower.",
    light: "Bright indirect light",
    water: "Weekly",
    temperature: "18-28 C",
  },
  {
    id: 8,
    name: "Snow Princess",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1744867719956-b3a0cb733400?auto=format&fit=crop&w=900&q=80",
    color: "White",
    origin: "Korea",
    category: "Phalaenopsis",
    description:
      "Layered white petals with a faint blush at the throat. Compact and slow to finish.",
    light: "Medium indirect light",
    water: "Weekly",
    temperature: "18-27 C",
  },
  {
    id: 9,
    name: "Pink Lady",
    rating: 4,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1595726555534-5a3f722cf278?auto=format&fit=crop&w=900&q=80",
    color: "Pink",
    origin: "Taiwan",
    category: "Dendrobium",
    description:
      "Soft pink sprays from a compact cane plant that flowers readily in a bright window.",
    light: "Bright filtered light",
    water: "Every 7-9 days",
    temperature: "18-28 C",
  },
  {
    id: 10,
    name: "Green Fairy",
    rating: 3,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1710524977643-7f65b64f2564?auto=format&fit=crop&w=900&q=80",
    color: "Green",
    origin: "Indonesia",
    category: "Paphiopedilum",
    description:
      "Lady slipper orchid with mottled leaves and small slipper pouches in fresh green.",
    light: "Shade to filtered light",
    water: "Keep evenly moist",
    temperature: "18-25 C",
  },
  {
    id: 11,
    name: "Royal Velvet",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1611201357633-2d5587c82099?auto=format&fit=crop&w=900&q=80",
    color: "Violet",
    origin: "Vietnam",
    category: "Vanda",
    description:
      "Velvety violet blooms with a contrasting magenta lip. The showpiece of the collection.",
    light: "Very bright light",
    water: "Daily misting",
    temperature: "20-32 C",
  },
  {
    id: 12,
    name: "Morning Star",
    rating: 4,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1693792352664-155c911e14a6?auto=format&fit=crop&w=900&q=80",
    color: "Yellow",
    origin: "Philippines",
    category: "Oncidium",
    description:
      "Golden sprays that open at dawn and smell faintly of vanilla.",
    light: "Bright indirect light",
    water: "Twice a week",
    temperature: "18-30 C",
  },
  {
    id: 13,
    name: "Ruby Love",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1760192635145-6a32d84ccf15?auto=format&fit=crop&w=900&q=80",
    color: "Red",
    origin: "Thailand",
    category: "Cattleya",
    description:
      "Rich ruby petals with a golden throat. Needs a bright spot and a cooler winter rest.",
    light: "Bright indirect light",
    water: "Weekly, dry between",
    temperature: "16-26 C",
  },
  {
    id: 14,
    name: "Lavender Dream",
    rating: 4,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1610391660739-1081cea2b408?auto=format&fit=crop&w=900&q=80",
    color: "Lavender",
    origin: "Japan",
    category: "Phalaenopsis",
    description:
      "Pale lavender blooms with fine speckling, an easy-going addition to any shelf.",
    light: "Medium indirect light",
    water: "Weekly",
    temperature: "18-28 C",
  },
  {
    id: 15,
    name: "Summer Breeze",
    rating: 3,
    isSpecial: false,
    image: "https://images.unsplash.com/photo-1648065611455-6774225ef654?auto=format&fit=crop&w=900&q=80",
    color: "Green",
    origin: "Singapore",
    category: "Cymbidium",
    description:
      "Teal-green petals on arching sprays. Long lasting once it settles into its new home.",
    light: "Bright light",
    water: "Weekly",
    temperature: "12-26 C",
  },
  {
    id: 16,
    name: "Sunset Glow",
    rating: 5,
    isSpecial: true,
    image: "https://images.unsplash.com/photo-1648066258914-6c5b207a0aa7?auto=format&fit=crop&w=900&q=80",
    color: "Orange",
    origin: "Malaysia",
    category: "Dendrobium",
    description:
      "Orange flowers with deep red veining, glowing in late afternoon light.",
    light: "Bright filtered light",
    water: "Every 7-9 days",
    temperature: "18-30 C",
  },
];

export default ListOfOrchids;
