const ListOfOrchids = [
  {
    id: 1,
    name: "Taichung Beauty",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/f8bbd0/333?text=Taichung+Beauty",
    color: "Pink",
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    id: 2,
    name: "White Moon",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/f5f5f5/333?text=White+Moon",
    color: "White",
    origin: "Thailand",
    category: "Dendrobium",
  },
  {
    id: 3,
    name: "Purple Queen",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/ce93d8/333?text=Purple+Queen",
    color: "Purple",
    origin: "Vietnam",
    category: "Phalaenopsis",
  },
  {
    id: 4,
    name: "Golden Sun",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/fff176/333?text=Golden+Sun",
    color: "Yellow",
    origin: "Japan",
    category: "Oncidium",
  },
  {
    id: 5,
    name: "Red Dragon",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/ef9a9a/333?text=Red+Dragon",
    color: "Red",
    origin: "China",
    category: "Cymbidium",
  },
  {
    id: 6,
    name: "Blue Diamond",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/90caf9/333?text=Blue+Diamond",
    color: "Blue",
    origin: "Singapore",
    category: "Vanda",
  },
  {
    id: 7,
    name: "Orange Delight",
    rating: 3,
    isSpecial: false,
    image: "https://placehold.co/600x400/ffcc80/333?text=Orange+Delight",
    color: "Orange",
    origin: "Malaysia",
    category: "Cattleya",
  },
  {
    id: 8,
    name: "Snow Princess",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/eeeeee/333?text=Snow+Princess",
    color: "White",
    origin: "Korea",
    category: "Phalaenopsis",
  },
  {
    id: 9,
    name: "Pink Lady",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/f48fb1/333?text=Pink+Lady",
    color: "Pink",
    origin: "Taiwan",
    category: "Dendrobium",
  },
  {
    id: 10,
    name: "Green Fairy",
    rating: 3,
    isSpecial: false,
    image: "https://placehold.co/600x400/a5d6a7/333?text=Green+Fairy",
    color: "Green",
    origin: "Indonesia",
    category: "Paphiopedilum",
  },
  {
    id: 11,
    name: "Royal Velvet",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/b39ddb/333?text=Royal+Velvet",
    color: "Violet",
    origin: "Vietnam",
    category: "Vanda",
  },
  {
    id: 12,
    name: "Morning Star",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/ffe082/333?text=Morning+Star",
    color: "Yellow",
    origin: "Philippines",
    category: "Oncidium",
  },
  {
    id: 13,
    name: "Ruby Love",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/e57373/333?text=Ruby+Love",
    color: "Red",
    origin: "Thailand",
    category: "Cattleya",
  },
  {
    id: 14,
    name: "Lavender Dream",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/d1c4e9/333?text=Lavender+Dream",
    color: "Lavender",
    origin: "Japan",
    category: "Phalaenopsis",
  },
  {
    id: 15,
    name: "Summer Breeze",
    rating: 3,
    isSpecial: false,
    image: "https://placehold.co/600x400/80cbc4/333?text=Summer+Breeze",
    color: "Green",
    origin: "Singapore",
    category: "Cymbidium",
  },
  {
    id: 16,
    name: "Sunset Glow",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/ffab91/333?text=Sunset+Glow",
    color: "Orange",
    origin: "Malaysia",
    category: "Dendrobium",
  },
];

export default ListOfOrchids;
