const ListOfOrchids = [
  {
    id: 1,
    name: "Taichung Beauty",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/f8bbd0/333?text=Taichung+Beauty",
    color: "Pink",
    origin: "Taiwan",
    category: "Cattleya",
    description:
      "A rare Cattleya hybrid known for its deep pink petals and a strong sweet fragrance that fills the room in the morning.",
    light: "Bright indirect light",
    water: "Weekly, once the mix dries",
    temperature: "18-28 C",
  },
  {
    id: 2,
    name: "White Moon",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/f5f5f5/333?text=White+Moon",
    color: "White",
    origin: "Thailand",
    category: "Dendrobium",
    description:
      "Pure white blooms on cane-like stems. Easy for beginners and reliable in a warm, humid corner.",
    light: "Filtered light",
    water: "Every 8-10 days",
    temperature: "16-27 C",
  },
  {
    id: 3,
    name: "Purple Queen",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/ce93d8/333?text=Purple+Queen",
    color: "Purple",
    origin: "Vietnam",
    category: "Phalaenopsis",
    description:
      "Moth orchid with a deep violet lip and long arching sprays that stay in flower for months.",
    light: "Medium indirect light",
    water: "Weekly",
    temperature: "18-29 C",
  },
  {
    id: 4,
    name: "Golden Sun",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/fff176/333?text=Golden+Sun",
    color: "Yellow",
    origin: "Japan",
    category: "Oncidium",
    description:
      "A dancing lady orchid with dozens of small butter-yellow flowers on branching spikes.",
    light: "Bright indirect light",
    water: "Twice a week",
    temperature: "18-30 C",
  },
  {
    id: 5,
    name: "Red Dragon",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/ef9a9a/333?text=Red+Dragon",
    color: "Red",
    origin: "China",
    category: "Cymbidium",
    description:
      "Bold crimson flowers on a sturdy plant that tolerates cooler rooms better than most orchids.",
    light: "Bright light",
    water: "Weekly",
    temperature: "12-24 C",
  },
  {
    id: 6,
    name: "Blue Diamond",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/90caf9/333?text=Blue+Diamond",
    color: "Blue",
    origin: "Singapore",
    category: "Vanda",
    description:
      "Unusual blue-violet tessellated petals. Vandas need airier roots, so keep the mix loose.",
    light: "Very bright light",
    water: "Daily misting",
    temperature: "20-32 C",
  },
  {
    id: 7,
    name: "Orange Delight",
    rating: 3,
    isSpecial: false,
    image: "https://placehold.co/600x400/ffcc80/333?text=Orange+Delight",
    color: "Orange",
    origin: "Malaysia",
    category: "Cattleya",
    description:
      "Warm apricot tones on medium blooms. A forgiving first orchid for a new grower.",
    light: "Bright indirect light",
    water: "Weekly",
    temperature: "18-28 C",
  },
  {
    id: 8,
    name: "Snow Princess",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/eeeeee/333?text=Snow+Princess",
    color: "White",
    origin: "Korea",
    category: "Phalaenopsis",
    description:
      "Layered white petals with a faint blush at the throat. Compact and slow to finish.",
    light: "Medium indirect light",
    water: "Weekly",
    temperature: "18-27 C",
  },
  {
    id: 9,
    name: "Pink Lady",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/f48fb1/333?text=Pink+Lady",
    color: "Pink",
    origin: "Taiwan",
    category: "Dendrobium",
    description:
      "Soft pink sprays from a compact cane plant that flowers readily in a bright window.",
    light: "Bright filtered light",
    water: "Every 7-9 days",
    temperature: "18-28 C",
  },
  {
    id: 10,
    name: "Green Fairy",
    rating: 3,
    isSpecial: false,
    image: "https://placehold.co/600x400/a5d6a7/333?text=Green+Fairy",
    color: "Green",
    origin: "Indonesia",
    category: "Paphiopedilum",
    description:
      "Lady slipper orchid with mottled leaves and small slipper pouches in fresh green.",
    light: "Shade to filtered light",
    water: "Keep evenly moist",
    temperature: "18-25 C",
  },
  {
    id: 11,
    name: "Royal Velvet",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/b39ddb/333?text=Royal+Velvet",
    color: "Violet",
    origin: "Vietnam",
    category: "Vanda",
    description:
      "Velvety violet blooms with a contrasting magenta lip. The showpiece of the collection.",
    light: "Very bright light",
    water: "Daily misting",
    temperature: "20-32 C",
  },
  {
    id: 12,
    name: "Morning Star",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/ffe082/333?text=Morning+Star",
    color: "Yellow",
    origin: "Philippines",
    category: "Oncidium",
    description:
      "Golden sprays that open at dawn and smell faintly of vanilla.",
    light: "Bright indirect light",
    water: "Twice a week",
    temperature: "18-30 C",
  },
  {
    id: 13,
    name: "Ruby Love",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/e57373/333?text=Ruby+Love",
    color: "Red",
    origin: "Thailand",
    category: "Cattleya",
    description:
      "Rich ruby petals with a golden throat. Needs a bright spot and a cooler winter rest.",
    light: "Bright indirect light",
    water: "Weekly, dry between",
    temperature: "16-26 C",
  },
  {
    id: 14,
    name: "Lavender Dream",
    rating: 4,
    isSpecial: false,
    image: "https://placehold.co/600x400/d1c4e9/333?text=Lavender+Dream",
    color: "Lavender",
    origin: "Japan",
    category: "Phalaenopsis",
    description:
      "Pale lavender blooms with fine speckling, an easy-going addition to any shelf.",
    light: "Medium indirect light",
    water: "Weekly",
    temperature: "18-28 C",
  },
  {
    id: 15,
    name: "Summer Breeze",
    rating: 3,
    isSpecial: false,
    image: "https://placehold.co/600x400/80cbc4/333?text=Summer+Breeze",
    color: "Green",
    origin: "Singapore",
    category: "Cymbidium",
    description:
      "Teal-green petals on arching sprays. Long lasting once it settles into its new home.",
    light: "Bright light",
    water: "Weekly",
    temperature: "12-26 C",
  },
  {
    id: 16,
    name: "Sunset Glow",
    rating: 5,
    isSpecial: true,
    image: "https://placehold.co/600x400/ffab91/333?text=Sunset+Glow",
    color: "Orange",
    origin: "Malaysia",
    category: "Dendrobium",
    description:
      "Orange flowers with deep red veining, glowing in late afternoon light.",
    light: "Bright filtered light",
    water: "Every 7-9 days",
    temperature: "18-30 C",
  },
];

export default ListOfOrchids;
